#----------------------------------------------------------------------
# This file was generated by C:\Python25\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

pencil = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAaJJ"
    "REFUOI210k9Ik3Ecx/HP9rjJY4/UJsUQF1nCHqn96eFRhn9GNXDs4sgIKoSokA7RJq0oyINT"
    "hoLkH6TSmruppy7RkFxEUotByTzINsRDdKhgEOywSYfx6eL52ST6nH8v3ofvD/jHCQd6rah3"
    "jB1H1iuitYJfPz8fLGVXhs49af5z9sNhImitwKkO1o5Ve8j79CjDefDe9mkqGy7qBuTfAKCv"
    "invkh323v886vAVIFRsGW8PoM7ZB/6O0W9Xqzp8a9byUOJwDI1mZX0txRr9co9RpSQJo0sa+"
    "45OO5yJvbYHRnMzNcpyR9GXWK+YEAEk7HbDMtszX0/8RHM+2M1Ne4sinAOtcja8AiJphXDIv"
    "NEwbaE+ADzJnuLUX46MNPwWHuAzAoF2+eugFpgSaVsGbKSc3SzHef++lzm6MoeqfuSKqx8bM"
    "RBwMvFOYKsYYSvYS7cK8NtzfyaB1aT09Qf9bD18XnvHGGzchY6omjOs44Xt8ocjyN67trFCd"
    "kwkbIrVhABgSFg39rXTf7c6bukwzkNBdOwaALt0kWnARVe/7H/YXNXiUVboIAxoAAAAASUVO"
    "RK5CYII=")

#----------------------------------------------------------------------
up = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAl9J"
    "REFUOI2lkktIVAEUhr97595xRjPMTGghA1m0sYieUOREQW2CFlq0aVkQkZSSlQsr0qIH9EBI"
    "StpV1CKhgugB2QOi1yKHyCJNa8ysKbvj3Nfce+e0KDMwUOhfHX7O/5/Dfw78J0L/pkUBfdfC"
    "BZtuxWJVjcnkoghseAQ3chP0PXi8ZvttMQ1LXMeVhoYOgaa2CYqb67ZsvikSBHL5rci5ThER"
    "kd31HQJNzeOJ4/GVF83A9eRyl8iaCzmpPGvJ6ftpCYKsVFVd9eDw+r8Vymh5oqioRHv49MHG"
    "iuGpJey/J6heFseySH2z2LMqj3iZyvylV7qTvfZyqB0AUEdCU0Juw7GjlRWFM0pofgCO4+E7"
    "Dr5tE7gOey/102sKLSfj5eGoNME+DUauoEUXr103+8yxQ3Ht2hv4/MND922+GzbOsEOhmqVQ"
    "CxgczLCtuoyej+bczlfpJwR33gFQOqs18fj5gNiuLxnbE/FsabmbknkHemR2XUJ2tnWJkUpJ"
    "X/KrDA19k8TrfonNaesD0AD8qBY52vrC9L2cgxNMPtK4RC+I5GGbDrbpEA5pfEm51B965tvZ"
    "wIjkhyJu+Fd8GsD3H9bq9otdxXh+FlVp3LF1bjUhDTdj4ZoW4ufx1XBpv97dQcarRdfCFEeM"
    "PwZ8qHkPvAeIxE4Zuq5gph0Mw8ROW2SGo6jqJApKo2lzqC6BB1iMbvA3RFU0VYEIOYp0n/yw"
    "TzSUQxQBTRnTP4ZAV8JZFDatKGHZzDx8z2falDA9nyzQ0Mc1yOZr3QfPv6R8ekGQy+V+f5tC"
    "MmWHnJDaN2bg/+InBgoq8St3ytkAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAm9J"
    "REFUOI2lk1tIVGEUhdc/V0cbzLyhlCGkaFCIEURJ0VMhvhVI9ZgQ2YOk9WAljEaBWWFlmRiF"
    "UEGmiBDTk9mkeYnC0rGyjLRSmotO4zln/jlnzvy7JzF0kKL1uNj7Y7FZG/hPseWGoeBWTeHm"
    "9LrMVFtU6FEADAYDgy+oGofGfM00cqx8VaI178bjp/3TREQkaYKCXCciolfjHoovuN27fN4U"
    "g6HGGwmDHqDtNcDlMIpzjciP08EYaSsSLzeIMR0g+CXA/YPDPR3CNx+HEAKMIGIn2NaSAY+c"
    "AkGqFlTtWkQAIgqmcpDGAd0KPSIQUiI2ZF7OhcFkQaI5iPET300AYLcZnVt3Z23QdcHB9eSU"
    "RAsmQirCCoeqcHCFsCbejF2F6TsUnXrizAbbh1nJFwDyTQAQJ9i6i1VFyVtykqBFdKQlMLzs"
    "k6FxFRoPI/BLICMpDS3ni6w2C1s/J+k4WNlrDCzewOdTjt588C6SZLeg+73AkfsLcI7KYBqH"
    "SVfhGptHsWMU9Y++INluQmv7BKamAseXjpg597yz6+Pdh08msDfXDPe0jM8zCoQaRlRT8XVm"
    "AcNjfhzYmYoXI3No6/jUCWJdSwBXrR4VJsfJ+sFJqybDsT8BXOKQJQ5FDiE4L+PcoSxsz1uL"
    "yoY3M2E1Uo3JCnVlA7IbS/aVdasRVaKae26yljgJe9qp9GwPSX4vHa5yErKvlsVs4B+Q2ooL"
    "vRQNL1D5lSEqPfOMgn4vOZr6CZuuN62+vKiNja2nL7nI5/GS3+OhuuYBQs61DoBW/E6sKgMp"
    "tvKGO6M/+956T1ktRrNrYLYJXK8GGP1dgn/Qb7rHPk5Y9SXmAAAAAElFTkSuQmCC")

