#----------------------------------------------------------------------
# This file was generated by C:\Python26\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

pencil = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAaJJ"
    "REFUOI210k9Ik3Ecx/HP9rjJY4/UJsUQF1nCHqn96eFRhn9GNXDs4sgIKoSokA7RJq0oyINT"
    "hoLkH6TSmruppy7RkFxEUotByTzINsRDdKhgEOywSYfx6eL52ST6nH8v3ofvD/jHCQd6rah3"
    "jB1H1iuitYJfPz8fLGVXhs49af5z9sNhImitwKkO1o5Ve8j79CjDefDe9mkqGy7qBuTfAKCv"
    "invkh323v886vAVIFRsGW8PoM7ZB/6O0W9Xqzp8a9byUOJwDI1mZX0txRr9co9RpSQJo0sa+"
    "45OO5yJvbYHRnMzNcpyR9GXWK+YEAEk7HbDMtszX0/8RHM+2M1Ne4sinAOtcja8AiJphXDIv"
    "NEwbaE+ADzJnuLUX46MNPwWHuAzAoF2+eugFpgSaVsGbKSc3SzHef++lzm6MoeqfuSKqx8bM"
    "RBwMvFOYKsYYSvYS7cK8NtzfyaB1aT09Qf9bD18XnvHGGzchY6omjOs44Xt8ocjyN67trFCd"
    "kwkbIrVhABgSFg39rXTf7c6bukwzkNBdOwaALt0kWnARVe/7H/YXNXiUVboIAxoAAAAASUVO"
    "RK5CYII=")

#----------------------------------------------------------------------
up = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAl9J"
    "REFUOI2lkktIVAEUhr97595xRjPMTGghA1m0sYieUOREQW2CFlq0aVkQkZSSlQsr0qIH9EBI"
    "StpV1CKhgugB2QOi1yKHyCJNa8ysKbvj3Nfce+e0KDMwUOhfHX7O/5/Dfw78J0L/pkUBfdfC"
    "BZtuxWJVjcnkoghseAQ3chP0PXi8ZvttMQ1LXMeVhoYOgaa2CYqb67ZsvikSBHL5rci5ThER"
    "kd31HQJNzeOJ4/GVF83A9eRyl8iaCzmpPGvJ6ftpCYKsVFVd9eDw+r8Vymh5oqioRHv49MHG"
    "iuGpJey/J6heFseySH2z2LMqj3iZyvylV7qTvfZyqB0AUEdCU0Juw7GjlRWFM0pofgCO4+E7"
    "Dr5tE7gOey/102sKLSfj5eGoNME+DUauoEUXr103+8yxQ3Ht2hv4/MND922+GzbOsEOhmqVQ"
    "CxgczLCtuoyej+bczlfpJwR33gFQOqs18fj5gNiuLxnbE/FsabmbknkHemR2XUJ2tnWJkUpJ"
    "X/KrDA19k8TrfonNaesD0AD8qBY52vrC9L2cgxNMPtK4RC+I5GGbDrbpEA5pfEm51B965tvZ"
    "wIjkhyJu+Fd8GsD3H9bq9otdxXh+FlVp3LF1bjUhDTdj4ZoW4ufx1XBpv97dQcarRdfCFEeM"
    "PwZ8qHkPvAeIxE4Zuq5gph0Mw8ROW2SGo6jqJApKo2lzqC6BB1iMbvA3RFU0VYEIOYp0n/yw"
    "TzSUQxQBTRnTP4ZAV8JZFDatKGHZzDx8z2falDA9nyzQ0Mc1yOZr3QfPv6R8ekGQy+V+f5tC"
    "MmWHnJDaN2bg/+InBgoq8St3ytkAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAm9J"
    "REFUOI2lk1tIVGEUhdc/V0cbzLyhlCGkaFCIEURJ0VMhvhVI9ZgQ2YOk9WAljEaBWWFlmRiF"
    "UEGmiBDTk9mkeYnC0rGyjLRSmotO4zln/jlnzvy7JzF0kKL1uNj7Y7FZG/hPseWGoeBWTeHm"
    "9LrMVFtU6FEADAYDgy+oGofGfM00cqx8VaI178bjp/3TREQkaYKCXCciolfjHoovuN27fN4U"
    "g6HGGwmDHqDtNcDlMIpzjciP08EYaSsSLzeIMR0g+CXA/YPDPR3CNx+HEAKMIGIn2NaSAY+c"
    "AkGqFlTtWkQAIgqmcpDGAd0KPSIQUiI2ZF7OhcFkQaI5iPET300AYLcZnVt3Z23QdcHB9eSU"
    "RAsmQirCCoeqcHCFsCbejF2F6TsUnXrizAbbh1nJFwDyTQAQJ9i6i1VFyVtykqBFdKQlMLzs"
    "k6FxFRoPI/BLICMpDS3ni6w2C1s/J+k4WNlrDCzewOdTjt588C6SZLeg+73AkfsLcI7KYBqH"
    "SVfhGptHsWMU9Y++INluQmv7BKamAseXjpg597yz6+Pdh08msDfXDPe0jM8zCoQaRlRT8XVm"
    "AcNjfhzYmYoXI3No6/jUCWJdSwBXrR4VJsfJ+sFJqybDsT8BXOKQJQ5FDiE4L+PcoSxsz1uL"
    "yoY3M2E1Uo3JCnVlA7IbS/aVdasRVaKae26yljgJe9qp9GwPSX4vHa5yErKvlsVs4B+Q2ooL"
    "vRQNL1D5lSEqPfOMgn4vOZr6CZuuN62+vKiNja2nL7nI5/GS3+OhuuYBQs61DoBW/E6sKgMp"
    "tvKGO6M/+956T1ktRrNrYLYJXK8GGP1dgn/Qb7rHPk5Y9SXmAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
fileclose = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAulJ"
    "REFUOI2lk09oWwUcxz/vX9PXZEnW1G2V6ObWP2m7lJU5qLQHZ6nebAfbYVeHzIPgSUE6dhsM"
    "PHjZweFJPPQy2EUUJiIM3VbNUliaBmzy0jRt/jTJS5o07yV77yUepIWJu7jv6csPvl++P36/"
    "L7wihH8Pzp9/J6Sq0mcnTry+4PMdHXAcm0KhqGez6R9N0/xa07TYS92mp6evX7v2SfPBg1+6"
    "hUKpa5rPu7q+311fT3eXl+93FxevWIODg18A8oFGOiAzMzPXL16c/+bmzRtKMBgkEDhKs2li"
    "GCaiKOFyublwYVas1+vz29ta0zRbvx8azM7Ojk9MhO8vLS3J5bLO9vYOu7s6iqLQaBikUhl6"
    "ejqYZpuxsSlSqb/eq1bLP7Tb7bwIIAjCp5cvX+lV1V729/cJh4dRFIGNjQxbWzsMDBxhairE"
    "8eM+qtUGc3MfSrIsf8nBLj5f/6VazUEUJVTVTTqdY3T0LQQhg213CIfPoGk5IpENLKuLYZj4"
    "/YH5SqWCCOB2+wLZbJF7937C7e6jVmuRTO5w+vQbjI6eQtNyPHz4DMOwWF//g3J5B1X1eA4T"
    "OI6Nosgkk5tsbmYYGRnm2LFxentdCIKIKMroeoV4PIJlNfF6X8NxbIB/EtTre9V2u4UgdGi3"
    "nxMKnWJk5CTZbJFkMsvQ0JssLLyLx9OHbVvYtkO9vmccXsHv90709w+eU1UPV68ucvbsMLlc"
    "iTt3vuXRoxVCoRBDQycJhyd58iRKoVBkbS36s+PYyxJAIHAk3Wq1Pg4Gz4iKIuL1erh79zu2"
    "tjQajRprawnGx8dYXV0lkUgRjT7ulEr5j4CsBLC7WylC23CczvuWJbOyEiGfzyCKAtClWi0R"
    "iTwjkUgRi60Sj0dvAd+/8ImTk+f+jMWiZrVampNlVfD5+pGkHmRZQVHc5PN5nj59TDwevQ3c"
    "Aqz/LFMg4H1bFF2f+/0DH7hcfR7Hsdnbqxm6Xvy11Wp9Bfz20jL9H/wNqm1HeNfAGaIAAAAA"
    "SUVORK5CYII=")

