# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sat Apr 11 16:08:04 2009
from appcommon.gui.hotkeyctrl import HotkeyCtrl
from appcommon.i18n import _
from libnavi.model.options import Options
from pubsub import pub
import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class OptionsDialog(wx.Dialog):
    def __init__(self, parent, options):
        self.options = options
        # begin wxGlade: OptionsDialog.__init__
        style = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, parent, style=style)
        self.main_notebook = wx.Notebook(self, -1, style=0)
        self.view_pane = wx.Panel(self.main_notebook, -1)
        self.font_lbl = wx.StaticText(self.view_pane, -1, _("Font"))
        self.actual_font_lbl = wx.StaticText(self.view_pane, -1, "")
        self.button_1 = wx.Button(self.view_pane, -1, _("Change..."))
        self.hotkey_lbl = wx.StaticText(self.view_pane, -1, _("Hotkey"))
        self.hotkey = HotkeyCtrl(self.view_pane, -1)
        self.btn_ok = wx.Button(self, wx.ID_OK, "")
        self.btn_cancel = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_font_change_click, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.on_ok_click, self.btn_ok)
        self.Bind(wx.EVT_BUTTON, self.on_cancel_click, self.btn_cancel)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: OptionsDialog.__set_properties
        self.SetTitle(_("Options"))
        # end wxGlade
        self.hotkey.SetHotkey(self.options.key_code, self.options.modifiers, False)

    def __do_layout(self):
        # begin wxGlade: OptionsDialog.__do_layout
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        std_diag_sizer = wx.StdDialogButtonSizer()
        view_sizer = wx.BoxSizer(wx.VERTICAL)
        font_sizer = wx.BoxSizer(wx.HORIZONTAL)
        view_sizer.Add(self.font_lbl, 0, wx.LEFT|wx.RIGHT|wx.TOP, 5)
        font_sizer.Add(self.actual_font_lbl, 1, 0, 0)
        font_sizer.Add(self.button_1, 0, 0, 0)
        view_sizer.Add(font_sizer, 0, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 5)
        view_sizer.Add(self.hotkey_lbl, 0, wx.LEFT|wx.RIGHT|wx.TOP, 5)
        view_sizer.Add(self.hotkey, 0, wx.ALL|wx.EXPAND, 5)
        self.view_pane.SetSizer(view_sizer)
        self.main_notebook.AddPage(self.view_pane, _("View"))
        main_sizer.Add(self.main_notebook, 1, wx.ALL|wx.EXPAND, 5)
        std_diag_sizer.AddButton(self.btn_ok)
        std_diag_sizer.AddButton(self.btn_cancel)
        std_diag_sizer.Realize()
        main_sizer.Add(std_diag_sizer, 0, wx.ALL|wx.EXPAND, 5)
        self.SetSizer(main_sizer)
        main_sizer.Fit(self)
        self.Layout()
        # end wxGlade

    def on_font_change_click(self, event): # wxGlade: OptionsDialog.<event_handler>
        event.Skip()

    def on_ok_click(self, event): # wxGlade: OptionsDialog.<event_handler>
        opt = Options()
        opt.modifiers = self.hotkey.GetModifiers()
        opt.key_code = self.hotkey.GetKeyCode()
        pub.sendMessage('options.changing', options=opt)
        event.Skip()

    def on_cancel_click(self, event): # wxGlade: OptionsDialog.<event_handler>
        event.Skip()

# end of class OptionsDialog


