# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sat Apr 11 16:08:04 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade
def _(x): return x

class OptionsDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: OptionsDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.main_notebook = wx.Notebook(self, -1, style=0)
        self.view_pane = wx.Panel(self.main_notebook, -1)
        self.font_lbl = wx.StaticText(self.view_pane, -1, _("Font"))
        self.actual_font_lbl = wx.StaticText(self.view_pane, -1, "")
        self.button_1 = wx.Button(self.view_pane, -1, _("Change..."))
        self.btn_ok = wx.Button(self, wx.ID_OK, "")
        self.btn_cancel = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: OptionsDialog.__set_properties
        self.SetTitle(_("Options"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: OptionsDialog.__do_layout
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        std_diag_sizer = wx.StdDialogButtonSizer()
        view_sizer = wx.BoxSizer(wx.VERTICAL)
        font_sizer = wx.BoxSizer(wx.HORIZONTAL)
        view_sizer.Add(self.font_lbl, 0, wx.LEFT|wx.RIGHT|wx.TOP, 5)
        font_sizer.Add(self.actual_font_lbl, 1, 0, 0)
        font_sizer.Add(self.button_1, 0, 0, 0)
        view_sizer.Add(font_sizer, 1, wx.ALL|wx.EXPAND, 5)
        self.view_pane.SetSizer(view_sizer)
        self.main_notebook.AddPage(self.view_pane, _("View"))
        main_sizer.Add(self.main_notebook, 1, wx.ALL|wx.EXPAND, 5)
        std_diag_sizer.AddButton(self.btn_ok)
        std_diag_sizer.AddButton(self.btn_cancel)
        std_diag_sizer.Realize()
        main_sizer.Add(std_diag_sizer, 0, wx.ALL|wx.EXPAND, 5)
        self.SetSizer(main_sizer)
        main_sizer.Fit(self)
        self.Layout()
        # end wxGlade

# end of class OptionsDialog


